apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: aeropuerto-front:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: http://backend-service:8080