apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
data:
  init.sql: |
    CREATE USER 'aeropuerto_user'@'%' IDENTIFIED BY 'securepassword';
    GRANT ALL PRIVILEGES ON aeropuerto_db.* TO 'aeropuerto_user'@'%';
    FLUSH PRIVILEGES;

    USE aeropuerto_db;

    CREATE TABLE pasajeros (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nombre VARCHAR(150) NOT NULL,
        apellido VARCHAR(150) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );