# Configuración para desarrollo con H2 (base de datos en memoria)
spring.datasource.url=jdbc:h2:mem:aeropuerto_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Hibernate validará el esquema generado por Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.sql.init.mode=never
spring.h2.console.enabled=true
server.port=8090
