// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const url = import.meta.env.VITE_SUPABASE_URL?.trim() ?? "";
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ?? "";

/** Sin estas variables el SDK no debe bloquear la app (solo API/MySQL en backend). */
export const isSupabaseConfigured = Boolean(url && key);

// createClient exige URL y clave no vacías; valores ficticios solo para cargar el bundle sin Supabase real.
const FALLBACK_URL = "https://placeholder.invalid.supabase.co";
const FALLBACK_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Import the supabase client like this:
// import { supabase, isSupabaseConfigured } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  isSupabaseConfigured ? url : FALLBACK_URL,
  isSupabaseConfigured ? key : FALLBACK_KEY,
  {
    auth: {
      storage: typeof localStorage !== "undefined" ? localStorage : undefined,
      persistSession: isSupabaseConfigured,
      autoRefreshToken: isSupabaseConfigured,
    },
  }
);
